import type { ContingencyPreviewRecord, ContingencyStatusCard, SyncOperationStatus } from './types';

export const contingencyStatusCards: ContingencyStatusCard[] = [
  {
    id: 'client-api',
    label: 'Cliente / API',
    value: 'Disponible · demo local',
    detail: 'Dato de demostración. Sin consulta HTTP al backend.',
    tone: 'success',
  },
  {
    id: 'dgi-provider',
    label: 'DGI / Proveedor',
    value: 'Sin consulta HTTP',
    detail: 'Estado no autoritativo. La WebApp no está consultando DGI ni proveedor.',
    tone: 'neutral',
  },
  {
    id: 'formal-contingency',
    label: 'Contingencia formal CFC',
    value: 'Inactiva · demo local',
    detail: 'Solo representación visual. Entrar o salir de contingencia permanece bloqueado.',
    tone: 'info',
  },
  {
    id: 'sync-queue',
    label: 'Sincronización',
    value: '6 registros de muestra',
    detail: 'Cola local determinista. No existe batch enviado ni replay contra API.',
    tone: 'warning',
  },
];

export const syncStatusLabels: Record<SyncOperationStatus, string> = {
  APPLIED: 'Aplicada',
  ALREADY_APPLIED: 'Ya aplicada',
  REJECTED: 'Rechazada',
  CONFLICT: 'Conflicto',
  REVIEW_REQUIRED: 'Requiere revisión',
  DEPENDENCY_BLOCKED: 'Dependencia bloqueada',
};

export const contingencyPreviewRecords: ContingencyPreviewRecord[] = [
  {
    id: 'cfc-demo-0042',
    kind: 'CFC',
    reference: 'CFC-DEMO-0042',
    source: 'Caja local · dispositivo 02',
    createdAt: '23/09/2026 · 08:42',
    status: 'REVIEW_REQUIRED',
    statusLabel: syncStatusLabels.REVIEW_REQUIRED,
    tone: 'warning',
    summary: 'Documento CFC de demostración conservado con su identidad original para revisión visual.',
    evidence: 'Identidad local CFC preservada. Sin reserva ni asignación de numeración normal CAE/CFE.',
    canonicalResult: 'API pendiente · sin resultado canónico del servidor.',
    recovery: 'Revisión requerida antes de cualquier reconciliación real.',
    history: [
      { at: '08:42', title: 'Registro local de demostración', detail: 'El fixture representa una operación creada durante contingencia formal.' },
      { at: '08:44', title: 'Marcada para revisión', detail: 'No se ejecutó reconciliación ni mutación contra backend.' },
    ],
  },
  {
    id: 'sync-demo-a71f',
    kind: 'SYNC',
    reference: 'OP-DEMO-A71F',
    source: 'Cliente offline · dispositivo 04',
    createdAt: '23/09/2026 · 08:57',
    status: 'APPLIED',
    statusLabel: syncStatusLabels.APPLIED,
    tone: 'success',
    summary: 'Resultado ilustrativo para mostrar el estado contractual Aplicada.',
    evidence: 'Fixture local determinista. No hubo replay HTTP ni confirmación DGI.',
    canonicalResult: 'Referencia demo SRV-DEMO-118 · no autoritativa.',
    recovery: 'Sin acción local pendiente en el preview.',
    history: [
      { at: '08:57', title: 'Operación local creada', detail: 'ID único de demostración para visualizar idempotencia.' },
      { at: '09:01', title: 'Estado Aplicada simulado', detail: 'Solo representa el estado contractual, sin efecto servidor.' },
    ],
  },
  {
    id: 'sync-demo-b204',
    kind: 'SYNC',
    reference: 'OP-DEMO-B204',
    source: 'Cliente offline · dispositivo 04',
    createdAt: '23/09/2026 · 09:02',
    status: 'ALREADY_APPLIED',
    statusLabel: syncStatusLabels.ALREADY_APPLIED,
    tone: 'info',
    summary: 'Ejemplo visual de replay idempotente de una operación ya conocida.',
    evidence: 'Mismo ID y mismo payload dentro del fixture local.',
    canonicalResult: 'Resultado demo reutilizado · sin consulta HTTP.',
    recovery: 'No requiere acción dentro del preview.',
    history: [
      { at: '09:02', title: 'Replay de demostración', detail: 'La UI ilustra el contrato de idempotencia sin ejecutar sincronización.' },
    ],
  },
  {
    id: 'sync-demo-c911',
    kind: 'SYNC',
    reference: 'OP-DEMO-C911',
    source: 'Cliente offline · dispositivo 07',
    createdAt: '23/09/2026 · 09:11',
    status: 'CONFLICT',
    statusLabel: syncStatusLabels.CONFLICT,
    tone: 'danger',
    summary: 'Conflicto ilustrativo: mismo ID local con payload materialmente distinto.',
    evidence: 'Comparación demo detecta diferencia material. No se infieren permisos ni autoridad servidor.',
    canonicalResult: 'Sin resultado canónico · API pendiente.',
    recovery: 'Requiere análisis antes de intentar recuperación real.',
    history: [
      { at: '09:11', title: 'Conflicto de demostración detectado', detail: 'Representación visual del caso contractual 409.' },
    ],
  },
  {
    id: 'sync-demo-d530',
    kind: 'SYNC',
    reference: 'OP-DEMO-D530',
    source: 'Cliente offline · dispositivo 03',
    createdAt: '23/09/2026 · 09:18',
    status: 'REJECTED',
    statusLabel: syncStatusLabels.REJECTED,
    tone: 'danger',
    summary: 'Operación de muestra rechazada para representar validación contractual.',
    evidence: 'Motivo demo: payload incompleto. No representa respuesta live 422.',
    canonicalResult: 'Sin referencia servidor · API pendiente.',
    recovery: 'Corregir origen antes de una futura revalidación autoritativa.',
    history: [
      { at: '09:18', title: 'Validación local ilustrativa', detail: 'El estado Rechazada es exclusivamente de demostración.' },
    ],
  },
  {
    id: 'sync-demo-e882',
    kind: 'SYNC',
    reference: 'OP-DEMO-E882',
    source: 'Cliente offline · dispositivo 05',
    createdAt: '23/09/2026 · 09:24',
    status: 'DEPENDENCY_BLOCKED',
    statusLabel: syncStatusLabels.DEPENDENCY_BLOCKED,
    tone: 'neutral',
    summary: 'Operación de muestra bloqueada por una dependencia previa todavía no resuelta.',
    evidence: 'La dependencia es fixture local; no se consultó estado servidor.',
    canonicalResult: 'Pendiente · sin consulta HTTP.',
    recovery: 'Esperar resolución autoritativa de la dependencia en una integración futura.',
    history: [
      { at: '09:24', title: 'Dependencia bloqueada', detail: 'Representación visual del orden de replay sin efectos laterales.' },
    ],
  },
];
